title: "Jorge Santos: Curriculum Vitae"
description: A journey through my career.
url: https://jsantos.github.io/cv
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
